### ISSUE TITLE
openapi spec 3.0

### ISSUE THREAD

**Issue by pitasi** [Pitasi/pick-a-movie#1]
currently the generated docs by the backend is a swagger file version 2.0, is there a way to have a 3.0 file?

**Comment by AzraelSec** [comment]
It seems not supported yet by the module we are using :roll_eyes: https://github.com/swaggo/swag/issues/386.
A workaround proposal is ready, but I'd avoid it if not really necessary.

**Comment by lifegit** [comment]
[swaggo/swag #386](https://github.com/swaggo/swag/issues/386)

Excuse me, I don't understand how to use it, would you like to help me ?
